//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.21 at 09:01:09 AM MSK
//


package com.alexeybelyaev.rates.cbr.dto;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="ValuteCursDynamic"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CursDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                   &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                   &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "valuteCursOnDate"
})

@XmlRootElement(name = "ValuteData", namespace = "")
public class ValuteData {

    @XmlElement(name = "ValuteCursOnDate", namespace = "")
    protected List<ValuteCursOnDate> valuteCursOnDate;

    /**
     * Gets the value of the valuteCursDynamic property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuteCursDynamic property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuteCursDynamic().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValuteCursOnDate }
     */
    public List<ValuteCursOnDate> getValuteCursOnDate() {
        if (valuteCursOnDate == null) {
            valuteCursOnDate = new ArrayList<ValuteCursOnDate>();
        }
        return this.valuteCursOnDate;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CursDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *         &lt;element name="Vcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Vnom" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *         &lt;element name="Vcurs" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "cursDate",
            "vcode",
            "vchCode",
            "vnom",
            "vname",
            "vcurs"
    })
    public static class ValuteCursOnDate {

        @XmlElement(name = "CursDate", namespace = "")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar cursDate;
        @XmlElement(name = "Vcode", namespace = "")
        protected String vcode;
        @XmlElement(name = "VchCode", namespace = "")
        protected String vchCode;
        @XmlElement(name = "Vname", namespace = "")
        protected String vname;
        @XmlElement(name = "Vnom", namespace = "")
        protected BigDecimal vnom;
        @XmlElement(name = "Vcurs", namespace = "")
        protected BigDecimal vcurs;

        public String getName() {
            return vname;
        }

        public void setName(String name) {
            this.vname = name;
        }

        public String getVchCode() {
            return vchCode;
        }

        public void setVchCode(String vchCode) {
            this.vchCode = vchCode;
        }

        /**
         * Gets the value of the cursDate property.
         *
         * @return possible object is
         * {@link XMLGregorianCalendar }
         */
        public XMLGregorianCalendar getCursDate() {
            return cursDate;
        }

        /**
         * Sets the value of the cursDate property.
         *
         * @param value allowed object is
         *              {@link XMLGregorianCalendar }
         */
        public void setCursDate(XMLGregorianCalendar value) {
            this.cursDate = value;
        }

        /**
         * Gets the value of the vcode property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getVcode() {
            return vcode;
        }

        /**
         * Sets the value of the vcode property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setVcode(String value) {
            this.vcode = value;
        }

        /**
         * Gets the value of the vnom property.
         *
         * @return possible object is
         * {@link BigDecimal }
         */
        public BigDecimal getVnom() {
            return vnom;
        }

        /**
         * Sets the value of the vnom property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setVnom(BigDecimal value) {
            this.vnom = value;
        }

        /**
         * Gets the value of the vcurs property.
         *
         * @return possible object is
         * {@link BigDecimal }
         */
        public BigDecimal getVcurs() {
            return vcurs;
        }

        /**
         * Sets the value of the vcurs property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setVcurs(BigDecimal value) {
            this.vcurs = value;
        }

    }

}
